name: Scheduled verify

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  schedule:
    # * Run the test every M, W, F at 12:30 UTC (7:30am CDT)
    - cron:  '30 12 * * 1,3,5'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  verify:
    uses: ./.github/workflows/verify-workflow.yaml
    secrets:
      IBMCLOUD_API_KEY: ${{ secrets.IBMCLOUD_API_KEY }}
      AWS_CLUSTER_USERNAME: ${{ secrets.AWS_CLUSTER_USERNAME }}
      AWS_CLUSTER_PASSWORD: ${{ secrets.AWS_CLUSTER_PASSWORD }}
      AZURE_CLUSTER_USERNAME: ${{ secrets.AZURE_CLUSTER_USERNAME }}
      AZURE_CLUSTER_PASSWORD: ${{ secrets.AZURE_CLUSTER_PASSWORD }}
      DISCORD_AUTOMATION_HOOK_URL: ${{ secrets.DISCORD_AUTOMATION_HOOK_URL }}

  notify:
    needs: [verify]
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - name: Notify discord
        uses: th0th/notify-discord@v0.4.1
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_AUTOMATION_HOOK_URL }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_JOB_NAME: "Verify"
          GITHUB_JOB_STATUS: ${{ needs.verify.outputs.status }}
